<?php
if(isset($_POST['str']))
{
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();
$str=$_POST['str'];

curl_setopt($ch, CURLOPT_URL, 'https://api.openai.com/v1/completions');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
$postdata=array( "model"=> "text-davinci-001",
"prompt"=>$str,
"temperature"=> 1,
"max_tokens"=> 256,
"top_p"=> 1,
"frequency_penalty"=> 0,
"presence_penalty"=> 0);
$postdata=json_encode($postdata);
curl_setopt($ch, CURLOPT_POSTFIELDS, $postdata);
$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Authorization:Bearer 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';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
 
$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
$result=json_decode($result,true);
//echo '<pre>';
//print_r($result['choices'][0]['text']);
echo $result['choices'][0]['text'];
}


?>  
<form method="post">
    <input type="text" name="str" required width="50%">
    <input type="submit" name="submit" value="Enter">
</form>     




document.getElementById("scrapeChat").addEventListener("click", function() {
        chrome.tabs.query({ active: true, currentWindow: true }, function(tabs) {
          chrome.scripting.executeScript({
            target: { tabId: tabs[0].id },
            function: accessAttribute
          });
        });
      });
      
      function accessAttribute() {
        // This function will be injected into the current tab's context
        // finding length l for access last div of querySelectorAll return... 
        
        var l=document.querySelectorAll('[role="row"]').length;
        var lastDiv=document.querySelectorAll('[role="row"]')[l-1];
        var message=lastDiv.outerText.split("\n");
        var childDiv=lastDiv.querySelector('.CzM4m');
        var person_status=childDiv.getAttribute("data-id").split("_");
      
        // alert("last chat :\n " + message[0] +"   from  " + person_status[0]);
         
       
       
      
        let x= Boolean(document.getElementById("main"));
       console.log(message[0]);
       if(!x)
       {
        document.getElementsByClassName("box")[0].innerHTML ='<div class="chat1"> Please select a chat </div>';
       }  
       else{
        
        document.getElementsByClassName("box")[0].innerHTML ='<div class="chat1">this is your last messatg</div>';
         
       }
      